apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    url: $PG_HOST:5432
    database: $PG_DB
    user: iaq_ro
    secureJsonData:
      password: $IAQ_RO_PW
    jsonData:
      database: $PG_DB
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: true
